#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
Regenerates docs/LICENSE_AUDIT.md from installed Python packages.
Usage:
  python3 scripts/license-audit.py          # regenerate in place
  python3 scripts/license-audit.py --check  # check if committed version is stale (CI mode)
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
AUDIT_FILE = REPO_ROOT / "docs" / "LICENSE_AUDIT.md"

NON_COMMERCIAL_PACKAGES = {
    "f5-tts": "CC-BY-NC-4.0 — NON-COMMERCIAL ONLY",
    "coqui-tts": "MPL-2.0 (code) / CPML (XTTS-v2 model weights) — model weights NON-COMMERCIAL ONLY",
}

KNOWN_PROBLEMATIC = {
    "pymupdf": "AGPL-3.0 — self-hosted source-available use is compliant; binary distribution requires source",
}


def get_package_licenses() -> list[dict[str, str]]:
    result = subprocess.run(
        [sys.executable, "-m", "piplicenses", "--format=json", "--with-urls"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"pip-licenses failed: {result.stderr}", file=sys.stderr)
        return []
    import json
    return json.loads(result.stdout)


def render_audit(packages: list[dict[str, str]]) -> str:
    from datetime import date

    lines = [
        "# License Audit — LectureVoice",
        "",
        f"> **Generated by:** `scripts/license-audit.py`  ",
        f"> **Last updated:** {date.today().isoformat()}  ",
        "> **Status:** Current",
        "",
        "This file is CI-enforced. Run `make license-audit` after any dependency change.",
        "",
        "---",
        "",
        "## Critical Non-Commercial Constraints ⚠️",
        "",
        "| Package | License |",
        "|---|---|",
    ]
    for pkg, note in NON_COMMERCIAL_PACKAGES.items():
        lines.append(f"| **{pkg}** | {note} |")

    lines += [
        "",
        "---",
        "",
        "## All Python Dependencies",
        "",
        "| Package | Version | License |",
        "|---|---|---|",
    ]
    for pkg in sorted(packages, key=lambda p: p["Name"].lower()):
        name = pkg["Name"]
        version = pkg["Version"]
        license_ = pkg.get("License", "UNKNOWN")
        flag = ""
        if name.lower() in {k.lower() for k in NON_COMMERCIAL_PACKAGES}:
            flag = " ⚠️"
        elif name.lower() in {k.lower() for k in KNOWN_PROBLEMATIC}:
            flag = " ⚠️"
        lines.append(f"| {name} | {version} | {license_}{flag} |")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="CI mode: exit 1 if audit is stale")
    args = parser.parse_args()

    try:
        packages = get_package_licenses()
    except Exception as exc:
        print(f"Could not collect package licenses: {exc}", file=sys.stderr)
        print("Install pip-licenses: pip install pip-licenses", file=sys.stderr)
        return 1

    new_content = render_audit(packages)

    if args.check:
        existing = AUDIT_FILE.read_text() if AUDIT_FILE.exists() else ""
        if existing.strip() != new_content.strip():
            print("LICENSE_AUDIT.md is stale. Run: make license-audit")
            return 1
        print("LICENSE_AUDIT.md is up to date.")
        return 0

    AUDIT_FILE.write_text(new_content)
    print(f"Written: {AUDIT_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
